import 'package:isar/isar.dart';
import 'package:business_sahaj_erp/data/local/collections/category_collection.dart';
import 'package:business_sahaj_erp/domain/repositories/category_repository.dart';
import 'package:business_sahaj_erp/data/repositories/base_isar_repository.dart';
import 'package:business_sahaj_erp/core/errors/exceptions.dart';

class CategoryRepositoryImpl extends BaseIsarRepository<Category> implements CategoryRepository {
  CategoryRepositoryImpl(Isar isar) : super(isar, 'Category');

  @override
  IsarCollection<Category> get collection => isar.collection<Category>();

  @override
  Future<List<Category>> getParentCategories() async {
    try {
      // In Isar, to fetch categories with no parent:
      // We can use parentCategoryIsNull query filter generated by Isar
      return await collection
          .filter()
          .isDeletedEqualTo(false)
          .parentCategoryIsNull()
          .findAll();
    } catch (e) {
      throw DatabaseException('Failed to retrieve parent categories: $e');
    }
  }

  @override
  Future<List<Category>> getSubCategories(int parentId) async {
    try {
      return await collection
          .filter()
          .isDeletedEqualTo(false)
          .parentCategory((q) => q.idEqualTo(parentId))
          .findAll();
    } catch (e) {
      throw DatabaseException('Failed to retrieve subcategories: $e');
    }
  }
}
