$text = [System.IO.File]::ReadAllText('lib\features\sales\presentation\screens\add_edit_invoice_screen.dart')
$text = $text.Replace('AddEditInvoiceScreen', 'AddEditCreditNoteScreen')
$text = $text.Replace('invoiceCartProvider', 'creditNoteCartProvider')
$text = $text.Replace('InvoiceItem', 'CreditNoteItem')
$text = $text.Replace('invoiceRepositoryProvider', 'creditNoteRepositoryProvider')
$text = $text.Replace('salesmen_list', 'credit_note_salesmen_list')
$text = $text.Replace('InvoiceData', 'CreditNoteData')
$text = $text.Replace('Invoice ', 'Credit Note ')
$text = $text.Replace('invoice.invoiceType', 'invoice.transactionType')
$text = $text.Replace('New Sales Invoice', 'Credit Note')
$text = $text.Replace('invoice_providers.dart', 'transaction_providers.dart')
$text = $text.Replace('invoice_collection.dart', 'credit_note_collection.dart')
$text = $text.Replace('invoice_item_collection.dart', 'credit_note_item_collection.dart')
$text = $text.Replace('_invoiceType', '_creditNoteType')
$text = $text.Replace('_invoiceDate', '_creditNoteDate')
$text = $text.Replace('generateNextInvoiceNumber', 'generateNextCreditNoteNumber')
$text = $text.Replace('saveInvoice', 'saveCreditNote')
$text = $text.Replace('Invoice? _existingInvoice;', 'CreditNote? _existingCreditNote;')
$text = $text.Replace('_existingInvoice = invoice;', '_existingCreditNote = invoice;')
$text = $text.Replace('Invoice? invoice;', 'CreditNote? invoice;')
$text = $text.Replace('invoice.invoiceNumber', 'invoice.creditNoteNumber')
$text = $text.Replace('invoice.invoiceDate', 'invoice.creditNoteDate')
$text = $text.Replace('db.invoices.filter()', 'db.creditNotes.filter()')
$text = $text.Replace('db.invoiceItems', 'db.creditNoteItems')
[System.IO.File]::WriteAllText('lib\features\transactions\presentation\screens\add_edit_credit_note_screen.dart', $text)
